site_name: Tutorial Frontend - Backend

nav:
  - Bienvenido!: index.md
  - Agradecimientos!: thanks.md
  - Contexto de la aplicaci칩n: usecases.md
  - Entorno de desarrollo:
    - 游댯 Angular: install/angular.md
    - 游릭 Springboot: install/springboot.md
    - 游릭 Nodejs: install/nodejs.md
  - Estructura y buenas pr치cticas:
    - 游댯 Angular: cleancode/angular.md
    - 游릭 Springboot: cleancode/springboot.md
    - 游릭 Nodejs: cleancode/nodejs.md
  - "Code: Listado simple":
    - 游댯 Angular: develop/basic/angular.md
    - 游릭 Springboot: develop/basic/springboot.md
    - 游릭 Nodejs: develop/basic/nodejs.md
  - "Code: Listado paginado":
    - 游댯 Angular: develop/paginated/angular.md
    - 游릭 Springboot: develop/paginated/springboot.md
    - 游릭 Nodejs: develop/paginated/nodejs.md
  - "Code: Listado filtrado":    
    - 游댯 Angular: develop/filtered/angular.md
    - 游릭 Springboot: develop/filtered/springboot.md
    - 游릭 Nodejs: develop/filtered/nodejs.md
  - Ahora hazlo tu!: exercise.md
  - "Anexos": 
    - "GIT: Tutorial b치sico": appendix/git.md
    - API Rest: appendix/rest.md
    - TDD: appendix/tdd.md
    - "Spring Data: JPA": appendix/jpa.md

theme:
    name: material
    language: es
    features:
      - navigation.path
      - navigation.indexes
    
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - codehilite
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences
  - markdown.extensions.toc:
      permalink: false
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
extra_css:
  - assets/style.css  
site_dir: 'site/dev'

