site_name: Tutorial Frontend - Backend

nav:
  - Bienvenido!: index.md
  - Agradecimientos!: thanks.md
  - Contexto de la aplicaci칩n: usecases.md
  - Entorno de desarrollo:
    - 游댯 Angular: install/angular.md
    - 游댯 React: install/react.md
    - 游댯 Vue.js: install/vuejs.md
    - 游릭 Spring Boot: install/springboot.md
    - 游릭 Nodejs: install/nodejs.md
  - Estructura y buenas pr치cticas:
    - 游댯 Angular: cleancode/angular.md
    - 游댯 React: cleancode/react.md
    - 游댯 Vue.js: cleancode/vuejs.md
    - 游릭 Spring Boot: cleancode/springboot.md
    - 游릭 Nodejs: cleancode/nodejs.md
  - "Code: Listado simple":
    - 游댯 Angular: develop/basic/angular.md
    - 游댯 Angular 17+: develop/basic/angular17.md
    - 游댯 React: develop/basic/react.md
    - 游댯 Vue.js: develop/basic/vuejs.md
    - 游릭 Spring Boot: develop/basic/springboot.md
    - 游릭 Nodejs: develop/basic/nodejs.md
  - "Code: Listado paginado":
    - 游댯 Angular: develop/paginated/angular.md
    - 游댯 Angular 17+: develop/paginated/angular17.md
    - 游댯 React: develop/paginated/react.md
    - 游댯 Vue.js: develop/paginated/vuejs.md
    - 游릭 Spring Boot: develop/paginated/springboot.md
    - 游릭 Nodejs: develop/paginated/nodejs.md
  - "Code: Listado filtrado":    
    - 游댯 Angular: develop/filtered/angular.md
    - 游댯 Angular 17+: develop/filtered/angular17.md
    - 游댯 React: develop/filtered/react.md
    - 游댯 Vue.js: develop/filtered/vuejs.md
    - 游릭 Spring Boot: develop/filtered/springboot.md
    - 游릭 Nodejs: develop/filtered/nodejs.md
  - Ahora hazlo t칰!: exercise.md
  - "Anexos": 
    - "GIT: Tutorial b치sico": appendix/git.md
    - API Rest: appendix/rest.md
    - TDD: appendix/tdd.md
    - "Spring Data: JPA": appendix/jpa.md
    - Spring Cloud:
        - Introducci칩n: appendix/springcloud/intro.md
        - Listado simple: appendix/springcloud/basic.md
        - Listado paginado: appendix/springcloud/paginated.md
        - Listado filtrado: appendix/springcloud/filtered.md
        - Infraestructura: appendix/springcloud/infra.md
        - Resumen: appendix/springcloud/summary.md
    - Spring Batch:
        - Introducci칩n: appendix/springbatch/intro.md
        - Fichero a BBDD: appendix/springbatch/filetodb.md
        - Fichero a Fichero: appendix/springbatch/filetofile.md
        - Limpieza: appendix/springbatch/clean.md
        - Resumen: appendix/springbatch/summary.md
        - Ahora hazlo t칰!: appendix/springbatch/exercise.md
    - Docker칤zate:
      - Instalar docker: appendix/docker/installdocker.md
      - 쯈u칠 es docker?: appendix/docker/docudocker.md
      - Practiquemos: appendix/docker/traindocker.md
      - Resumen: appendix/docker/summary.md
    - AWS CLI: appendix/aws.md
theme:
    name: material
    language: es
    features:
      - navigation.path
      - navigation.indexes
    
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - codehilite
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences
  - markdown.extensions.toc:
      permalink: false
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
extra_css:
  - assets/style.css  

not_in_nav: |
  /develop/basic/vuejsold.md



